"""Criar vencimento fatura

Revision ID: 073738d69c2a
Revises: 401e2e3b0cd6
Create Date: 2025-05-14 16:51:38.769876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073738d69c2a'
down_revision: Union[str, None] = '401e2e3b0cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_input', sa.Column('vencimento_fatura', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_input', 'vencimento_fatura')
    # ### end Alembic commands ###
