"""Aumentar o tamanho de chave_nfe

Revision ID: 1085eddfa9ce
Revises: 073738d69c2a
Create Date: 2025-05-15 11:39:44.936894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1085eddfa9ce'
down_revision: Union[str, None] = '073738d69c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cte_info', 'chave_nfe',
               existing_type=sa.VARCHAR(length=44),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cte_info', 'chave_nfe',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=44),
               existing_nullable=True)
    # ### end Alembic commands ###
