"""Criação da tabela user_input

Revision ID: 3deb1beee993
Revises: 08034604096d
Create Date: 2025-05-07 10:45:22.163567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3deb1beee993'
down_revision: Union[str, None] = '08034604096d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome_cliente', sa.String(length=100), nullable=False),
    sa.Column('numero_cte', sa.String(length=20), nullable=False),
    sa.Column('numero_fatura', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_input_id'), 'user_input', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_input_id'), table_name='user_input')
    op.drop_table('user_input')
    # ### end Alembic commands ###
