"""Criar user_input_cte_linkv2

Revision ID: 401e2e3b0cd6
Revises: ff51230cde14
Create Date: 2025-05-08 16:32:43.858616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401e2e3b0cd6'
down_revision: Union[str, None] = 'ff51230cde14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input_cte_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input_id', sa.Integer(), nullable=False),
    sa.Column('cte_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cte_info_id'], ['cte_info.id'], ),
    sa.ForeignKeyConstraint(['user_input_id'], ['user_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_input_cte_link_id'), 'user_input_cte_link', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_input_cte_link_id'), table_name='user_input_cte_link')
    op.drop_table('user_input_cte_link')
    # ### end Alembic commands ###
