"""criação da tabela de referencia dos ids de cte com id do user input

Revision ID: 9f10a2a4011b
Revises: 00cd428550a5
Create Date: 2025-05-08 14:24:49.645674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f10a2a4011b'
down_revision: Union[str, None] = '00cd428550a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
