"""Tabelas iniciais

Revision ID: e0c0e6fa31c1
Revises: 
Create Date: 2025-05-06 17:40:27.314758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c0e6fa31c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cte_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.String(length=10), nullable=False),
    sa.Column('numero_cte', sa.Integer(), nullable=False),
    sa.Column('serie_cte', sa.Integer(), nullable=True),
    sa.Column('cnpj_cliente', sa.String(length=20), nullable=True),
    sa.Column('valor_receber', sa.Numeric(precision=13, scale=2), nullable=True),
    sa.Column('valor_prestacao', sa.Numeric(precision=13, scale=2), nullable=True),
    sa.Column('valor_mercadoria', sa.Numeric(precision=13, scale=2), nullable=True),
    sa.Column('peso_mercadoria', sa.Numeric(precision=13, scale=2), nullable=True),
    sa.Column('chave_nfe', sa.String(length=44), nullable=True),
    sa.Column('cnpj_destinatario', sa.String(length=20), nullable=True),
    sa.Column('nome_destinatario', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cte_info_id'), 'cte_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cte_info_id'), table_name='cte_info')
    op.drop_table('cte_info')
    # ### end Alembic commands ###
