"""removido a coluna numero_cte do user_input

Revision ID: ee687a7fbdde
Revises: 9f10a2a4011b
Create Date: 2025-05-08 14:51:34.927955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee687a7fbdde'
down_revision: Union[str, None] = '9f10a2a4011b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_input', 'numero_cte')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_input', sa.Column('numero_cte', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
